### PR TITLE
Add AWSCloudFormationReadOnlyAccess policy to `SetupRole`

### PR DESCRIPTION
**Pull request by danni-m**
This fixes the permissions issue raised in #135.
I haven't tested this e2e yet, please be aware.

### CODE REVIEW

**Comment by danni-m** [comment]
We tested this fix on our AWS account and we got consistent success.

**Comment by jaymccon** [comment]
Thanks for the contribution @danni-m 😃 

While it's difficult for me to test the effectiveness of this (I have not been able to replicate #135) the fix looks reasonable. I'll merge to develop branch, let ci run on it, and lets see if it fixes this issue for others.

**Comment by danni-m** [comment]
@jaymccon thanks!

**Comment by pierreozoux** [comment]
developping on top of this quickstart, for the last days, I've been fine, and since today (for whatever reason) I hit the issue.
Applying your fix, fixed it.

**Comment by pierreozoux** [comment]
This is really strange...
The initial policy should work, i tested it in https://policysim.aws.amazon.com/ and I got a green light..
There is something I don't understand.

**Comment by pierreozoux** [comment]
By the way, @danni-m @jaymccon you should join https://commons.openshift.org/ there is a slack community, just asked for an AWS channel :)

**Pull request merged**
