### PR TITLE
fix for issue #9 clarify instructions

### PR DESCRIPTION
**Pull request by dougtoppin**
Added some overview that might help anyone not familiar with RH subscriptions.

### CODE REVIEW

**Comment by avattathil** [comment]
Thank you for the contribution. Please confirm you accept the terms of Apache 2.0 so I can merge

**Comment by dougtoppin** [comment]
Yep, I accept the Apache 2.0 terms.

**Comment by avattathil** [comment]
0124645812

**Comment by ngerasimatos** [comment]
What is 0124645812?

**Pull request merged**
