### PR TITLE
Update submodule pull method

### PR DESCRIPTION
**Pull request by as0bu**
Use https vs ssh for submodule updates/pulls.

### CODE REVIEW

**Comment by santiagocardenas** [comment]
I'd suggest going with:
```
[submodule "submodules/quickstart-aws-vpc"]
	path = submodules/quickstart-aws-vpc
	url = ../../aws-quickstart/quickstart-aws-vpc.git
[submodule "submodules/quickstart-linux-utilities"]
	path = submodules/quickstart-linux-utilities
	url =../../aws-quickstart/quickstart-linux-utilities.git
```

That way it follows the protocol... git/ssh for build systems and https for casual cloners.

**Comment by as0bu** [comment]
Pull request #42 implements this. Thanks for that info. Today I learned something new!

**Comment by santiagocardenas** [comment]
Dilly Dilly! :)

**Comment by as0bu** [comment]
Dilly Dilly!

**Comment by avattathil** [comment]
Dilly Dilly!

**Pull request merged**
