### PR TITLE
Changes to allow 1AZ and fix to scaler operations

### PR DESCRIPTION
**Pull request by shaithal**
*Issue #, if available:*

*Description of changes:*
Added changes to support 1/3 AZ's. For now changes are done at openshift.template so that the feature can be availed in our quickstarts. By default Openshift QS still supports only 3 AZ's.

Fixed issue related to scale down. 

Added changes from shrumit to support Ansible post install script and ansible playbook parameters.

Updated Min max values of ASG's. Expanded worker nodes to support max of 20. 

Added AnsibleStorageSize to define disk capacity of Ansible controller server from our QS.

Added ASG's and ELB to output values for now. We are evaluating the requirement yet.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shaithal** [comment]
@vsnyc @jaymccon

**Comment by jaymccon** [comment]
waiting for one more change before merge

**Comment by shaithal** [comment]
[taskcat_outputs.zip](https://github.com/aws-quickstart/quickstart-redhat-openshift/files/3632532/taskcat_outputs.zip)

**Comment by shrumit** [comment]
@jaymccon All ok from the Datastage team. You can review and merge.

**Pull request merged**
